- block: 

  - name: UFW; modify ufw rules for Ubuntu
    ufw:
      state: enabled
      default: deny

  - name: UFW; allow ssh in by default
    ufw:
      rule: allow
      port: ssh
      proto: tcp

  - name: UFW; allow all traffic between cluster hosts
    ufw:
      rule: allow
      src: "{{ hostvars[item]['ansible_host'] }}"
    loop: "{{ groups['k3s-cluster'] }}"

  - name: UFW; allow all traffic on cni0 port
    ufw:
      rule: allow
      interface: "{{ item }}"
      direction: in
    loop: 
      - "cni0"
      - "docker0"
      - "flannel.1"

  - name: UFW; process any additional ports
    ufw:
      port: "{{ item.port }}"
      rule: "{{ item.rule }}"
      proto: "{{ item.proto }}"
      src: "{{ item.src }}"
    loop: "{{ K3S_FIREWALL_ADD_PORTS }}"
    when: K3S_FIREWALL_ADD_PORTS is defined

  when: ansible_distribution == "Ubuntu" and K3S_FIREWALL_MANAGE is defined and K3S_FIREWALL_MANAGE is true
