- name: Block for AlmaLinux and Rocky
  block:
  - name: SELINUX; set selinux to permissive
    ansible.posix.selinux:
      state: disabled

  - name: SHELL; update crypto policies
    shell: update-crypto-policies --set LEGACY
  when: ansible_distribution in ["AlmaLinux", "Rocky"]

- name: SERVICE; stop and disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: false
