---

- name: FILE; create /opt/k3s to be used for install log and passwords, if relevant
  file:
    path: /opt/k3s
    state: directory
    mode: 0755

- import_tasks: postgresql.yml
  when: inventory_hostname in groups['k3s-masters'] and K3S_POSTGRESQL_ENABLE is defined and K3S_POSTGRESQL_ENABLE|bool

- name: SHELL; uninstall if K3S_FORCE_UNINSTALL; if error, we'll assume it was already uninstalled
  shell: /usr/local/bin/k3s-uninstall.sh
  ignore_errors: true
  when: inventory_hostname in groups['k3s-cluster'] and K3S_FORCE_UNINSTALL is defined and K3S_FORCE_UNINSTALL|bool

- import_tasks: k3s-install.yml
